spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/customer_svc"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: customer-svc
server:
  port: 5750

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"